### ISSUE TITLE
회원가입시 description 미입력시 db insert 에러 발생

### ISSUE THREAD

**Issue by Coen90** [codeit-team3/BE#5]
Entity에서는 nullable = false 인데 request에서는 null이 올 수 있어 에러 발생합니다 ㅎㅎ
확인 부탁드립니다!

**Comment by jun-ha** [comment]
넵 확인했습니다! description은 한 줄 소개라 필수가 아닌데, 혹시 Entity에서 nullable=true로 하는게 나을까요? 아니면 회원가입시, 입력을 안하면 공백문자열을 임의로 넣는 방식이 나을까요?

**Comment by Coen90** [comment]
꼭 null일 필요는 없을것같고 null이면 오히려 후처리가 귀찮아질수 있을것같아서 빈 문자열로 처리하게 편할것같네요 ㅎㅎ

**Comment by jun-ha** [comment]
네넵 혹시 바로 dev에 푸시할까요?

**Comment by Coen90** [comment]
넵ㅎㅎ
