### ISSUE TITLE
PR Merge시에 squash 머지를 하면 어떨까 하는데.. 어떻게 생각하시나용?

### ISSUE THREAD

**Issue by Coen90** [codeit-team3/BE#6]
커밋로그를 하나로 합쳐서 커밋을 여러번해도 최상위 하나만 남게 되며, 상세 내용은 커밋 detail(정확하게는 어딘지 모르겠어요 😅)을 통해 확인 가능합니다!

이렇게하면 장점이 하나의 PR은 하나의 커밋로그만 남기게되서 전체 이력을 볼때 편하다? 라는 장점이 있습니다.
단점은 아직 잘 모르겠네요 ㅎㅎ

어떻게 생각하시나요?

참고자료 : https://techblog.woowahan.com/2553/

**Comment by jun-ha** [comment]
네넵 알겠습니다! 훨씬 보기 좋을 것 같네요 감사합니다ㅎㅎ

**Comment by Coen90** [comment]
pr merge시에 squash merge만 사용 가능하게 수정했습니다!
